image:
  name: azureml/curated/acft-hf-diffusion-gpu
  os: linux
  context:
    dir: context
    dockerfile: Dockerfile
    template_files:
    - Dockerfile
  publish:
    location: mcr
    visibility: unlisted
